In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('hour.csv')
dataset.head(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [3]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X.shape)
print(X)

(17379, 15)
[['2011-01-01' 1 0 ... 0.0 3 13]
 ['2011-01-01' 1 0 ... 0.0 8 32]
 ['2011-01-01' 1 0 ... 0.0 5 27]
 ...
 ['2012-12-31' 1 1 ... 0.1642 7 83]
 ['2012-12-31' 1 1 ... 0.1343 13 48]
 ['2012-12-31' 1 1 ... 0.1343 12 37]]


In [15]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Assuming 'dataset' is your DataFrame containing the features

try:
  # Convert the date column to datetime format (assuming it's parsable)
  dataset['dteday'] = pd.to_datetime(dataset.iloc[:, 1])  # Assign to existing column

  # Create a DataFrame with only the date column
  dates_df = dataset[['dteday']]

  # Apply one-hot encoding to the date DataFrame
  ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0])])
  encoded_dates = ct.fit_transform(dates_df)

  # Drop the original date column and add the encoded columns to dataset
  dataset.drop('dteday', axis=1, inplace=True)
  for col in range(encoded_dates.shape[1]):  # Assuming columns from encoding
    dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]

except (ValueError, AttributeError):  # Handle cases where date format is invalid
  print("Error: Could not parse date column. Please check the data format.")


C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset['date_encoded_' + str(col+1)] = encoded_dates[:, col]
C:\Program Files\KMSpico\temp\ipykernel_18752\2696044620.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

In [16]:
print(X.shape)
print(X)

(17379, 18)
[[1.0 0.0 0.0 ... 0.0 3 13]
 [1.0 0.0 0.0 ... 0.0 8 32]
 [1.0 0.0 0.0 ... 0.0 5 27]
 ...
 [1.0 0.0 0.0 ... 0.1642 7 83]
 [1.0 0.0 0.0 ... 0.1343 13 48]
 [1.0 0.0 0.0 ... 0.1343 12 37]]


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

ValueError: could not convert string to float: '2011-01-15'