# Support Vector Regression (SVR)

## Importing the libraries

In [42]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [43]:
dataset = pd.read_csv('hour.csv')
dataset.head(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [44]:
X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:, -1].values

In [45]:
print(X)

[[ 1.    0.    1.   ...  0.    3.   13.  ]
 [ 1.    0.    1.   ...  0.    8.   32.  ]
 [ 1.    0.    1.   ...  0.    5.   27.  ]
 ...
 [ 1.    1.   12.   ...  0.16  7.   83.  ]
 [ 1.    1.   12.   ...  0.13 13.   48.  ]
 [ 1.    1.   12.   ...  0.13 12.   37.  ]]


In [46]:
print(y)

[16 40 32 ... 90 61 49]


In [47]:
y = y.reshape(len(y),1)

In [48]:
print(y)

[[16]
 [40]
 [32]
 ...
 [90]
 [61]
 [49]]


In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [50]:
print("Trainig Data..")
print("The shape of training features: ", X_train.shape)
print("The shape of training labels: ", y_train.shape)
print("Testing Data..")
print("The shape of testing features: ", X_test.shape)
print("The shape of testing labels: ", y_test.shape)

Trainig Data..
The shape of training features:  (13903, 14)
The shape of training labels:  (13903, 1)
Testing Data..
The shape of testing features:  (3476, 14)
The shape of testing labels:  (3476, 1)


## Feature Scaling

In [51]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train_scaled = sc_X.fit_transform(X_train)
y_train_scaled = sc_y.fit_transform(y_train)
X_test_scaled = sc_y.fit_transform(X_test)
y_test_scaled = sc_y.fit_transform(y_test)

In [52]:
print(X)

[[ 1.    0.    1.   ...  0.    3.   13.  ]
 [ 1.    0.    1.   ...  0.    8.   32.  ]
 [ 1.    0.    1.   ...  0.    5.   27.  ]
 ...
 [ 1.    1.   12.   ...  0.16  7.   83.  ]
 [ 1.    1.   12.   ...  0.13 13.   48.  ]
 [ 1.    1.   12.   ...  0.13 12.   37.  ]]


In [53]:
print(y)

[[16]
 [40]
 [32]
 ...
 [90]
 [61]
 [49]]


## Training the SVR model on the whole dataset

In [54]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train_scaled, y_train_scaled)

C:\Users\admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting a new result

In [55]:
# Making predictions on the testing data
y_pred_scaled = regressor.predict(X_test_scaled)
y_pred = sc_y.inverse_transform(y_pred_scaled)
# Printing the predicted and actual values side by side
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

ValueError: Expected 2D array, got 1D array instead:
array=[ 1.28 -0.54 -1.01 ... -0.59  0.5   0.4 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
# Calculating and printing the testing accuracy
testing_acc = np.ceil(regressor.score(X_test_scaled, y_test_scaled) * 100)
print("The Testing_acc Accuracy = ", testing_acc, "%")

## Visualising the SVR results

In [ ]:
plt.scatter(y_train, X_train, color = 'red')
plt.plot(sc_X.inverse_transform(X), sc_y.inverse_transform(regressor.predict(X).reshape(-1,1)), color = 'blue')
plt.title('Truth or Bluff (SVR)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

## Visualising the SVR results (for higher resolution and smoother curve)

In [ ]:
X_grid = np.arange(min(sc_X.inverse_transform(X)), max(sc_X.inverse_transform(X)), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(sc_X.inverse_transform(X), sc_y.inverse_transform(y), color = 'red')
plt.plot(X_grid, sc_y.inverse_transform(regressor.predict(sc_X.transform(X_grid)).reshape(-1,1)), color = 'blue')
plt.title('Truth or Bluff (SVR)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()